### PR TITLE
feat: improve typing for query execution

### PR DESCRIPTION
**Pull request by affanshahid**
This PR improves the typing for the `executeQuery` and `executeQueryPriv` methods. It adds optional type parameters to enable well-typed queries and responses. Allowing the methods to be used like:

```ts
import type { Exograph } from "../generated/exograph-modified.d.ts";

interface VenuesQuery {
  venues: Array<{ name: string }>;
}

interface VenuesQueryVariables {
  param: string;
}

const venuesDocument = /* GraphQL */ `
query venues($param: String!) {
	venues(where: {name: {eq: $param}}) {
		 name
	}
}
`;

export async function process(exograph: Exograph): Promise<string> {
  const venues = await exograph.executeQuery<VenuesQuery, VenuesQueryVariables>(
    venuesDocument,
    {
      param: "Foo",
      // wrongParam: 'value' - Error: Object literal may only specify known properties
    },
  );

  // venues.venues.map(v => v.nonExistent).join(','); - Error: Property 'nonExistent' does not exist

  return venues.venues.map((v) => v.name).join(",");
}
```

You can also pair it with tools like [GraphQL Codegen](https://the-guild.dev/graphql/codegen) to automatically generate the types for your graphql queries based on the schema served by Exograph:

```ts
import type { Exograph } from "../generated/exograph-modified.d.ts"
import { VenuesQuery, VenuesQueryVariables } from "../generated/graphql.d.ts";

const venuesDocument = /* GraphQL */ `
query venues($param: String!) {
	venues(where: {name: {eq: $param}}) {
		 name
	}
}
`;

export async function process(exograph: Exograph): Promise<string> {
  const venues = await exograph.executeQuery<VenuesQuery, VenuesQueryVariables>(
    venuesDocument,
    {
      param: "Foo",
      // wrongParam: 'value' - Error: Object literal may only specify known properties
    },
  );

  // venues.venues.map(v => v.nonExistent).join(','); - Error: Property 'nonExistent' does not exist

  return venues.venues.map((v) => v.name).join(",");
}
```

This is helpful for a large project with a lot of deno modules, where Typescript can help you find issues with your queries, especially if you change the underlying schema and the queries need to be updated.

### CODE REVIEW

**Comment by ramnivas** [comment]
@affanshahid This is awesome! Thanks.

Please send the signed CLA (I sent it to your email) so that I can merge it and cut a new release.

**Comment by affanshahid** [comment]
Sent!

**Comment by affanshahid** [comment]
I just published https://github.com/affanshahid/exograph-deno-utils which makes generating and using types for GraphQL queries even easier. This is just something I hacked together, not sure if some of it can be built into Exograph at some point.

**Comment by ramnivas** [comment]
@affanshahid  This is awesome! Thank you for sharing.

Indeed, this can be added to Exograph itself, but requires a few pre-steps. I will outline them in a separate issue.

**Pull request merged**
